In [1]:
import numpy as np
import pandas as pd
from urllib.request import urlopen
import json

import plotly.io as pio 
import plotly.express as px #빠르게 사용
import plotly.graph_objects as go  #디테일하게 설정해야할때
import plotly.figure_factory as ff
from plotly.subplots import make_subplots # 여러 subplot을 그릴때 
from plotly.validators.scatter.marker import SymbolValidator # 마커사용

In [2]:
df = pd.read_excel("comparing_price_directly.xlsx", header=0, skipfooter=0)

In [3]:
#pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
#pd.set_option('display.width', 1000)
df.head()

,지역구,법정동,아파트,아파트코드,공급면적(㎡),전용면적(㎡),위도,경도,2017_2분기,2020_4분기
0,강남구,역삼동,역삼롯데캐슬노블,22320,51.01,176.03,37.492491,127.035424,140000,180000
1,강남구,도곡동,아카데미스위트,9218,38.93,122.07,37.488828,127.051585,115000,179000
2,강남구,도곡동,아카데미스위트,9218,38.18,83.00,37.488828,127.051585,85000,147000
3,강남구,도곡동,역삼우성,363,52.55,84.83,37.488557,127.036956,89800,177000
4,강남구,도곡동,개포우성5차,294,103.10,78.99,37.486029,127.047425,98800,170000

In [4]:
df

,지역구,법정동,아파트,아파트코드,공급면적(㎡),전용면적(㎡),위도,경도,2017_2분기,2020_4분기
0,강남구,역삼동,역삼롯데캐슬노블,22320,51.01,176.03,37.492491,127.035424,140000,180000
1,강남구,도곡동,아카데미스위트,9218,38.93,122.07,37.488828,127.051585,115000,179000
2,강남구,도곡동,아카데미스위트,9218,38.18,83.00,37.488828,127.051585,85000,147000
3,강남구,도곡동,역삼우성,363,52.55,84.83,37.488557,127.036956,89800,177000
4,강남구,도곡동,개포우성5차,294,103.10,78.99,37.486029,127.047425,98800,170000
...,...,...,...,...,...,...,...,...,...,...
3203,중랑구,묵동,신내5단지두산대림,811,196.07,126.28,37.616975,127.088246,51800,93500
3204,중랑구,묵동,묵동신도1차,3842,125.29,59.89,37.616938,127.077678,32000,57500
3205,중랑구,묵동,묵동신도1차,3842,125.62,84.89,37.616938,127.077678,40000,65000
3206,중랑구,묵동,신내4단지,10528,196.93,39.84,37.616724,127.084896,21350,39000
3207,중랑구,묵동,신내5단지두산대림,811,196.07,126.28,37.616975,127.088246,54600,91000

In [5]:
fig_moon = px.scatter_mapbox(df, lat="위도", lon="경도", color="지역구", size="세대수",
                  color_continuous_scale=px.colors.cyclical.IceFire, size_max=15, zoom=10,
                  mapbox_style="carto-positron")
fig_moon.show()

ValueError: Value of 'size' is not the name of a column in 'data_frame'. Expected one of ['지역구', '법정동', '아파트', '아파트코드', '공급면적(㎡)', '전용면적(㎡)', '위도', '경도', '2017_2분기', '2020_4분기'] but received: 세대수

In [ ]:
fig = px.scatter(data_frame=데이터프레임, x=x축, y=y축, log_[xy]=True or False로 x혹은 y축 스케일 로그변환,
                 color="지정한 컬럼(연속,카테고리다 가능)에 따른 다른색부여",
                 size="지정한 컬럼 값에 비례해 사이즈 반영",
                 size_max=크기값제한 int,
                 category_orders={"카테고리컬럼":["카테고리","순서","정함"]},
                 hover_data=["마우스를 올렸을때 추가적으로 보여줄 컬럼들"],
                 facet_[row,col]="속성값"에 따라 분리해서 row혹은col로 그림,
                 facet_col_wrap= facet_col컬럼기준 각 figure당 몇개의subplot즉, facet을 그릴지 지정 int,
                 labels={'x':'x축이름','y':'y축이름'},
                 trendline='ols' or 'lowess'locally weighted scatterplot sommthing line 추가,
                 title="제목",
                 text="각 데이터마다 보여줄 값 지정 컬럼",
                 range_x=["x축,범위지정"],
                 range_y=["y축,범위지정"],
                 width=None 픽셀단위크기 500~2000정도 적당한듯,
                 height=None 픽섹단위크기,
                 error_[xy]="컬럼"에러바,
                 error_[xy]_minus="컬럼"에러바 음수
                 opacity=int 불투명도, 
                 marginal_[xy]='rug'`, `'box'`, `'violin'`, or `'histogram'` x,y축 위로 옵션에 따른 그래프,
                 template = "템플릿"['ggplot2', 'seaborn', 'simple_white', 'plotly','plotly_white', 'plotly_dark', 'presentation', 'xgridoff','ygridoff', 'gridon', 'none']
                )

fig.update_xaxes(rangeslider_visible=True) # x축 범위 지정 슬라이드
fig.update_traces(texttemplate="%{text:.2s}", textposition='top center') # text가 숫자일시 몇자리까지 표시할지 지정, text 위치
fig.update_layout(height=800) # height(세로)조정
fig.show()